from .internal import OPERATORS_INTERNAL
from .fs       import OPERATORS_FS

OPERATORS_FOR_REGISTRATION = []
OPERATORS_FOR_REGISTRATION += OPERATORS_INTERNAL
OPERATORS_FOR_REGISTRATION += OPERATORS_FS